name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    # if: contains(github.event.issue.labels.*.name, 'deployed')
    steps:
      - name: Slash Command Dispatch
        id: scd
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.PAT }}
          commands: example,example-error
          repository: wayn3r/slash-command-processor
          issue-type: pull-request
          allow-edits: false
          reactions: false
      - name: Edit comment with error message
        if: steps.scd.outputs.error-message
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: test-id
          body: |
            > ${{ steps.scd.outputs.error-message }}